[info]
name = "clang"
version = "18.1.18"
default_programs = "../programs/clang"

[[steps]]
cmd = "clang"
flags = ["-Wall", "-Werror", "-O2"]
output_file = "a.out"
hidden = false
use_stdin = false

[[steps]]
cmd = "./a.out"
flags = []
output_file = ""
hidden = false
use_stdin = true

[temp_files]
dir = "/tmp/clang-compile"
prefix = "tmp_"
cleanup = true
